---
env:
  browser: true
  jquery: true
  node: true

globals:
  emp: true
  mil: true
  emp3: true
  cmapi: true
  $: true
  armyc2: true
  sec: true

extends:
  - eslint:recommended

rules:
  semi:
    - error
    - always
  no-console:
    - error
    - allow:
        - "warn"
        - "error"
  complexity:
    - off
    #- error # comment `off` out and `error` in to find places to reduce complexity
    - 6
  no-extra-bind: error
